[msg LMAP_DUMMY]
[f 0 5 -258][f 2 1]クマ[n][e]

[msg HELP_GO_STATION]
[f 0 5 -258][f 2 1]If you go to Okina, night will fall when[n]you leave.[n][f 1 1][e]

[msg MSG_GO_STATION]
[f 0 5 -258][f 2 1]> Spend time in Okina until evening?[n][f 1 1][e]

[sel SEL_GO_STATION]
[f 0 5 -258][f 2 1]Go to Okina[e]
[f 0 5 -258][f 2 1]Cancel[e]

[msg MSG_GO_SEA]
[f 0 5 -258][f 2 1]> Spend time sea fishing until evening?[n][f 1 1][e]

[sel SEL_GO_SEA]
[f 0 5 -258][f 2 1]Yes[e]
[f 0 5 -258][f 2 1]No[e]

[msg FLD_ORDER]
[f 0 5 -258][f 2 1]Where will you go?[n][f 1 1][e]

[sel STREET_SEL]
[f 0 5 -258][f 2 1]Shopping District, North[e]
[f 0 5 -258][f 2 1]Shopping District, South[e]
[f 0 5 -258][f 2 1]Shrine[e]
[f 0 5 -258][f 2 1]Cancel[e]

[sel SCHOOL_SEL]
[f 0 5 -258][f 2 1]Classroom Building, 1F[e]
[f 0 5 -258][f 2 1]Classroom Building, 2F[e]
[f 0 5 -258][f 2 1]Classroom Building, 3F[e]
[f 0 5 -258][f 2 1]Practice Building, 1F[e]
[f 0 5 -258][f 2 1]Practice Building, 2F[e]
[f 0 5 -258][f 2 1]Class 2-2[e]
[f 0 5 -258][f 2 1]Roof[e]
[f 0 5 -258][f 2 1]Cancel[e]

[sel SEL_EMBANK]
[f 0 5 -258][f 2 1]Flood Plain[e]
[f 0 5 -258][f 2 1]Riverbank[e]
[f 0 5 -258][f 2 1]Cancel[e]

